### ISSUE TITLE
exclude does not appear to work for JavaScript

### ISSUE THREAD

**Issue by Ziflin** [celsomiranda/hexo-beautify#3]
Using:

``` yaml
beautify:
  types:
     - html
     - css
     - js
  exclude:
     - "*.min.js"
     - "*.min.css"
...
```

I have been unable to prevent it from beautifying *.min.js files. I haven't checked *.min.css yet, but it may have the same problem.
